### ISSUE TITLE
 Please ask you a question about your other paper：A Joint Learning Framework for the CCKS-2020 Financial Event Extraction Task

### ISSUE THREAD

**Issue by npq567** [JiaweiSheng/CasEE#13]
Hello, I recently read another paper from you. I want to ask a question. 
How is the 'synthetic feature' implemented in this paper? Or is there any reference?
 Thank you for your contribution and look forward to your reply.

**Comment by JiaweiSheng** [comment]
Hi, I have replied you by email, so I close this issue.
