### ISSUE TITLE
Can not run

### ISSUE THREAD

**Issue by ItGirls** [JiaweiSheng/CasEE#3]
Hi, thank you to share your code! 
Here are some problems in your code, when i ran the main.py, it meet an error like this below :
"CasEE/utils/framework.py", line 71, in train 
token = torch.LongTensor(token).to(self.config.device)
ValueError: expected sequence of length 79 at dim 1 (got 83)
"
I find that in your code there's no padding to the tokens to the same length, maybe it's why it goes like this.

**Comment by JiaweiSheng** [comment]
Hi, ​I didn't reproduce this problem. 
Actually, the padding operation is in CasEE/utils/data_loader.py line 207.
Maybe it is caused by other reason. Please run the code as in readme.
