### ISSUE TITLE
Run with Multiple GPUs

### ISSUE THREAD

**Issue by yc1999** [JiaweiSheng/CasEE#5]
Hi, thanks for your code, it's an excellent work! 
I tried to run your code **with multiple gpus** using the following command:
```
CUDA_VISIBLE_DEVICES=5,4 python main.py --output_model_path ./models_save/model.bin --do_train True --do_eval True --do_test True > logs/model.log
```
But it turned out that only gpu 5 is used 😢 I don't konw whether you can run with multiple gpus, maybe this is a problem only caused by myself.

I guess it is because the following code:

https://github.com/JiaweiSheng/CasEE/blob/2c38fb33a50524e345407b037b4d501a9dd83067/utils/framework.py#L51

should be:
```
self.model = torch.nn.DataParallel(model) 
```

and also, to further realize running with multiple gpus, I also modified the following code:
https://github.com/JiaweiSheng/CasEE/blob/2c38fb33a50524e345407b037b4d501a9dd83067/models/model.py#L8
to:
```
self.register_buffer('type_indices', torch.arange(0, config.type_num, 1).long())
```
After the above two modifications, it works fine with multiple gpus.

**Comment by JiaweiSheng** [comment]
Hi! Thanks for your suggestion. I have modified the code as that. : )
